<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2014-07-30 16:22

$extensionPath = t3lib_extMgm::extPath('scheduler_timeline');
$extensionClassesPath = $extensionPath . 'Classes/';
return array(
	'ux_tx_scheduler' => $extensionPath . 'class.ux_tx_scheduler.php',
	'tx_schedulertimeline_controller_timelinecontroller' => $extensionClassesPath . 'Controller/TimelineController.php',
	'tx_schedulertimeline_domain_model_log' => $extensionClassesPath . 'Domain/Model/Log.php',
	'tx_schedulertimeline_domain_model_task' => $extensionClassesPath . 'Domain/Model/Task.php',
	'tx_schedulertimeline_domain_repository_logrepository' => $extensionClassesPath . 'Domain/Repository/LogRepository.php',
	'tx_schedulertimeline_domain_repository_taskrepository' => $extensionClassesPath . 'Domain/Repository/TaskRepository.php',
	'tx_schedulertimeline_returnmessage' => $extensionPath . 'interface.tx_schedulertimeline_returnmessage.php',
	'tx_schedulertimeline_scheduler_exceptiontask' => $extensionClassesPath . 'Scheduler/ExceptionTask.php',
	'tx_schedulertimeline_viewhelpers_durationviewhelper' => $extensionClassesPath . 'ViewHelpers/DurationViewHelper.php',
	'tx_schedulertimeline_viewhelpers_for_increaseviewhelper' => $extensionClassesPath . 'ViewHelpers/For/IncreaseViewHelper.php',
	'tx_schedulertimeline_viewhelpers_format_speakingdateviewhelper' => $extensionClassesPath . 'ViewHelpers/Format/SpeakingDateViewHelper.php',
	'tx_schedulertimeline_viewhelpers_ganttviewhelper' => $extensionClassesPath . 'ViewHelpers/GanttViewHelper.php',
	'tx_schedulertimeline_viewhelpers_statusviewhelper' => $extensionClassesPath . 'ViewHelpers/StatusViewHelper.php',
);
?>